config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    # no need for app/views/restaurants/update.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

  def set_task
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="col-xs-12">
    <%= form_for(@task) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :details %>
        <%= f.text_field :details, class: 'form-control' %>
      </div>

      <div class="form-group custom-control custom-checkbox">
        <%= f.check_box :completed%>
        Completed?
      </div>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>

    <div class="link padded">
      <%= link_to tasks_path do %>
        <i class="fa fa-undo" aria-hidden="true"> Back to checklist</i>
      <% end %>

    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="col-xs-12">
    <h1>My Tasks</h1>
    <% @tasks.each do |task| %>
      <div class="custom-control custom-checkbox">
        <% if task.completed %>
        <input type="checkbox" class="form-check-input" checked = true >
        <% else %>
        <input type="checkbox" class="form-check-input" checked = false>
        <% end %>
       <%= link_to task[:title], task_path(task) %>
       <%= link_to "Delete",
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
    <%= link_to "Add a new task", tasks_new_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="col-xs-12">
    <%= form_for(@task) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :details %>
        <%= f.text_field :details, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="col-xs-12">
    <div class="title">
      <%= @task.title %>
      <%= link_to edit_path(@task) %>
      <%= link_to task_path(params[:id]),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
    <!-- details -->
    <div class="details">
      <i class="fa fa-info-circle padded" aria-hidden="true"></i><%= @task.details %>
    </div>
    <div class="completed">
      <% if @task.completed %>
        <i class="fa fa-check-square-o padded"><%= ' this task is completed' %></i>
      <% else %>
        <i class="fa fa-square-o padded"><%= ' this task is NOT completed' %></i>
      <% end %>
    </div>
    <div class="backlink">
      <%= link_to "Update", edit_path(@task) %>
      <%= link_to 'Back to Checklist', tasks_path %>
    </div>
  </div>
</div>